repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-added-large-files
- repo: https://github.com/golangci/golangci-lint
  rev: v1.55.2
  hooks:
  - id: golangci-lint-full
- repo: local
  hooks:
  - id: goji-check
    name: Goji Check
    entry: goji check
    language: system
    stages: [commit-msg]
    types: [go]
    verbose: true
