builds:
- binary: goji
  main: ./
  goos:
  - darwin
  - linux
  goarch:
  - amd64
  - arm64
  env:
  - CGO_ENABLED=0
  flags:
  - -mod=vendor
  ldflags:
  - -s -w -X cmd.version={{.Version}}

release:
  prerelease: auto

universal_binaries:
- replace: true

brews:
- name: goji
  homepage: "https://github.com/muandane/homebrew-muandane"
  repository:
    owner: muandane
    name: homebrew-muandane
  folder: Formula
  commit_author:
    name: muandane
    email: zmoualhi@outlook.com

checksum:
  name_template: 'checksums.txt'
