name: test
on: [pull_request]
jobs:
  test:
    runs-on: self-hosted
    steps:
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.20.5'
    - name: Check out code
      uses: actions/checkout@v2
    - name: Test and generate coverage report
      run: cd src/ && go test -coverprofile=coverage.out ./...
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      env: 
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        file: coverage.out