name: test
on: [pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v4.1.0
      with:
        go-version: '1.21.4'
    - name: Check out code 
      uses: actions/checkout@v4.1.1
    - name: Test and generate coverage report
      run: cd src/ && go test -coverprofile=coverage.out ./...
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3.1.4
      env: 
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        file: coverage.out
